AWSTemplateFormatVersion: '2010-09-09'
Description: Module to create 2 EC2 instances in Public and Private Subnets

Parameters:
  VpcId:
    Type: String

  PublicSubnetId:
    Type: String

  PrivateSubnetId:
    Type: String

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

  AmiId:
    Type: AWS::EC2::Image::Id

Resources:
  # Public Security Group: Allows SSH from anywhere to the Public instance
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from anywhere
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Allows access from any IP address

  # Private Security Group: Allows SSH only from Public instance to the Private instance
  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from public instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicSecurityGroup # Allows access only from Public Security Group

  # Public Instance: EC2 instance in the Public Subnet with a public IP
  PublicInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref AmiId
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref PublicSecurityGroup
      Tags:
        - Key: Name
          Value: PublicInstance
      AssociatePublicIpAddress: true # Ensures the instance has a public IP to allow SSH from the internet

  # Private Instance: EC2 instance in the Private Subnet without a public IP
  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref AmiId
      KeyName: !Ref KeyName
      SubnetId: !Ref PrivateSubnetId
      SecurityGroupIds:
        - !Ref PrivateSecurityGroup
      Tags:
        - Key: Name
          Value: PrivateInstance
      AssociatePublicIpAddress: false # No public IP assigned to keep it private

Outputs:
  PublicInstanceId:
    Value: !Ref PublicInstance
    Description: The ID of the Public EC2 instance

  PrivateInstanceId:
    Value: !Ref PrivateInstance
    Description: The ID of the Private EC2 instance
