AWSTemplateFormatVersion: '2010-09-09'
Description: NAT Gateway with Elastic IP and Route Table

Parameters:
  PublicSubnetId:
    Type: String
  PrivateSubnetId:
    Type: String
  VpcId:
    Type: String

Resources:
  # Elastic IP for NAT Gateway
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  # NAT Gateway in Public Subnet
  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      SubnetId: !Ref PublicSubnetId

  # Private Route Table for routing traffic through NAT Gateway
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId

  # Private Route to NAT Gateway
  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  # Private Subnet Route Table Association
  PrivateSubnetAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetId
      RouteTableId: !Ref PrivateRouteTable

Outputs:
  NATGatewayId:
    Value: !Ref NATGateway
  EIP:
    Value: !Ref EIP
