AWSTemplateFormatVersion: '2010-09-09'
Description: Security Groups Module

Parameters:
  VPCId:
    Type: String
    Description: VPC ID

Resources:
  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: PublicSecurityGroup
      GroupDescription: Allow SSH and SCP from specific IP
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 171.250.164.134/32

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: PrivateSecurityGroup
      GroupDescription: Allow SSH from Public EC2
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicSecurityGroup

Outputs:
  PublicSecurityGroupId:
    Description: Public Security Group ID
    Value: !Ref PublicSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-PublicSecurityGroupId"
  PrivateSecurityGroupId:
    Description: Private Security Group ID
    Value: !Ref PrivateSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-PrivateSecurityGroupId"