version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-southeast-1

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo ">> Starting INSTALL phase at $(date)"
      - pip install --upgrade pip
      - pip install cfn-lint
      - pip install taskcat
      - echo ">> INSTALL phase completed at $(date)"

  pre_build:
    commands:
      - echo ">> Starting PRE-BUILD phase at $(date)"
      - python --version
      - pip --version
      - aws --version
      - cfn-lint --version
      - taskcat --version
      - test -f main.yaml && echo "Found main.yaml" || (echo "main.yaml not found!" && exit 1)
      - test -d Module && echo "Found Modules/ directory" || echo "Warning: Module/ directory not found"
      - echo ">> PRE-BUILD phase completed at $(date)"

  build:
    commands:
      - echo ">> Starting BUILD phase at $(date)"
      - echo "Running cfn-lint on main.yaml..."
      - cfn-lint main.yaml || (echo "cfn-lint failed on main.yaml, exiting." && exit 1)
      - echo "Running cfn-lint on Modules/*.yaml..."
      - cfn-lint Module/*.yaml || (echo "cfn-lint failed on module templates, exiting." && exit 1)
      - echo "Running AWS validate-template..."
      - aws cloudformation validate-template --template-body file://main.yaml || (echo "validate-template failed, exiting." && exit 1)
      - echo "Running taskcat tests..."
      - taskcat test run --no-delete | tee taskcat.log || (echo "taskcat test failed, see taskcat.log" && exit 1)
      - echo "Cleaning up taskcat test stacks..."
      - taskcat test clean ALL || echo "Warning: taskcat cleanup may have failed"
      - echo ">> BUILD phase completed at $(date)"

  post_build:
    commands:
      - echo ">> Starting POST-BUILD phase at $(date)"
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then
          echo "Build SUCCESSFUL. All checks passed.";
        else
          echo "Build FAILED. Please check log output above.";
        fi
      - echo ">> POST-BUILD phase completed at $(date)"

reports:
  taskcat-report:
    files:
      - taskcat_outputs/**/*

artifacts:
  files:
    - main.yaml
    - Modules/*.yaml
    - taskcat.log
    - taskcat_outputs/**/*
  name: lab2-unique-artifacts

cache:
  paths:
    - '/root/.cache/pip/**/*'
