AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack module VPC

Resources:
  VPCModule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://lab2-group13-bucket.s3.us-east-1.amazonaws.com/vpc.yaml #https://nhom13-cloudformation-1.s3.ap-southeast-1.amazonaws.com/modules/vpc.yaml
      Parameters:
        VpcCIDR: 10.0.0.0/16
        PublicSubnetCIDR: 10.0.1.0/24
        PrivateSubnetCIDR: 10.0.2.0/24

  NATGatewayModule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://lab2-group13-bucket.s3.us-east-1.amazonaws.com/nat-gateways.yaml #https://nhom13-cloudformation-1.s3.ap-southeast-1.amazonaws.com/modules/nat-gateway.yaml
      Parameters:
        VpcId: !GetAtt VPCModule.Outputs.VpcId
        PublicSubnetId: !GetAtt VPCModule.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCModule.Outputs.PrivateSubnetId

  EC2Module:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://lab2-group13-bucket.s3.us-east-1.amazonaws.com/ec2.yaml #https://nhom13-cloudformation-1.s3.ap-southeast-1.amazonaws.com/modules/ec2.yaml
      Parameters:
        VpcId: !GetAtt VPCModule.Outputs.VpcId
        PublicSubnetId: !GetAtt VPCModule.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCModule.Outputs.PrivateSubnetId
        KeyName: lab2-key13
        AmiId: ami-0c02fb55956c7d316  # Amazon Linux 2, us-east-1  #ami-0f3f13f145e66a0a3


Outputs:
  VpcId:
    Description: VPC ID from the VPC Module
    Value: !GetAtt VPCModule.Outputs.VpcId

  PublicSubnetId:
    Description: Public Subnet ID from the VPC Module
    Value: !GetAtt VPCModule.Outputs.PublicSubnetId

  PrivateSubnetId:
    Description: Private Subnet ID from the VPC Module
    Value: !GetAtt VPCModule.Outputs.PrivateSubnetId