AWSTemplateFormatVersion: '2010-09-09'
Description: Main template to create VPC, Subnets, EC2 instances and related resources

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://nhom13-lab1-cloudformation.s3.ap-southeast-1.amazonaws.com/modules/vpc.yaml

  SubnetsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://nhom13-lab1-cloudformation.s3.ap-southeast-1.amazonaws.com/modules/subnets.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId

  GatewaysStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SubnetsStack
    Properties:
      TemplateURL: https://nhom13-lab1-cloudformation.s3.ap-southeast-1.amazonaws.com/modules/gateways.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt SubnetsStack.Outputs.PublicSubnetId

  RouteTablesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: GatewaysStack
    Properties:
      TemplateURL: https://nhom13-lab1-cloudformation.s3.ap-southeast-1.amazonaws.com/modules/route-tables.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt SubnetsStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt SubnetsStack.Outputs.PrivateSubnetId
        InternetGatewayId: !GetAtt GatewaysStack.Outputs.InternetGatewayId
        NatGatewayId: !GetAtt GatewaysStack.Outputs.NatGatewayId

  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: RouteTablesStack
    Properties:
      TemplateURL: https://nhom13-lab1-cloudformation.s3.ap-southeast-1.amazonaws.com/modules/security-groups.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId

  EC2InstancesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SecurityGroupsStack
    Properties:
      TemplateURL: https://nhom13-lab1-cloudformation.s3.ap-southeast-1.amazonaws.com/modules/ec2.yaml
      Parameters:
        PublicSubnetId: !GetAtt SubnetsStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt SubnetsStack.Outputs.PrivateSubnetId
        PublicSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.PublicSecurityGroupId
        PrivateSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.PrivateSecurityGroupId

Outputs:
  VPCId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VPCId
  PublicInstanceId:
    Description: Public EC2 Instance ID
    Value: !GetAtt EC2InstancesStack.Outputs.PublicInstanceId
  PrivateInstanceId:
    Description: Private EC2 Instance ID
    Value: !GetAtt EC2InstancesStack.Outputs.PrivateInstanceId